### ISSUE TITLE
Build failed because `babel-cli` is incompatible with current react version

### ISSUE THREAD

**Issue by alechp** [aakashns/create-component-lib#7]
### Error
<details>
<summary>ReferenceError: [BABEL] src/lib/TextInput.js: Unknown option</summary>
> sample-lib@0.1.0 build /Users/alechp/Code/alechp/.repositories/sandbox/cra-lib/sample-lib
> rm -rf dist && NODE_ENV=production babel src/lib --out-dir dist --copy-files --ignore __tests__,spec.js,test.js,__snapshots__

ReferenceError: [BABEL] src/lib/TextInput.js: Unknown option: /Users/alechp/Code/alechp/.repositories/sandbox/cra-lib/sample-lib/node_modules/babel-preset-react-app/index.js.overrides. Check out http://babeljs.io/docs/usage/options/ for more information about options.

A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`

For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options. (While processing preset: "/Users/alechp/Code/alechp/.repositories/sandbox/cra-lib/sample-lib/node_modules/babel-preset-react-app/index.js")
    at Logger.error (/Users/alechp/Code/alechp/.repositories/sandbox/cra-lib/sample-lib/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/alechp/Code/alechp/.repositories/sandbox/cra-lib/sample-lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
    at /Users/alechp/Code/alechp/.repositories/sandbox/cra-lib/sample-lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
    at /Users/alechp/Code/alechp/.repositories/sandbox/cra-lib/sample-lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/alechp/Code/alechp/.repositories/sandbox/cra-lib/sample-lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/alechp/Code/alechp/.repositories/sandbox/cra-lib/sample-lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/alechp/Code/alechp/.repositories/sandbox/cra-lib/sample-lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/alechp/Code/alechp/.repositories/sandbox/cra-lib/sample-lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/alechp/Code/alechp/.repositories/sandbox/cra-lib/sample-lib/node_modules/babel-core/lib/transformation/file/index.js:212:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sample-lib@0.1.0 build: `rm -rf dist && NODE_ENV=production babel src/lib --out-dir dist --copy-files --ignore __tests__,spec.js,test.js,__snapshots__`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sample-lib@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alechp/.npm/_logs/2019-09-10T21_21_32_753Z-debug.log
</details>

### Fix
```
yarn remove babel-cli && yarn add @babel/cli
```

---

### Build Output Before
<img width="1792" alt="Screen Shot 2019-09-10 at 2 23 26 PM" src="https://user-images.githubusercontent.com/3058939/64651738-0e213f00-d3d7-11e9-8971-6a2fd2dde4c4.png">

### Build Output After
<img width="1792" alt="Screen Shot 2019-09-10 at 2 26 39 PM" src="https://user-images.githubusercontent.com/3058939/64651757-1a0d0100-d3d7-11e9-9ec5-3a6e5971a12a.png">

**Comment by sarawallebo** [comment]
I was experiencing the same problem, thank you for providing a fix 👍

**Comment by alechp** [comment]
> I was experiencing the same problem, thank you for providing a fix 👍

You're welcome

**Comment by bank8426** [comment]
Thank you very much. It's work.

**Comment by FontEndArt** [comment]
Thank you, Is this repositories still maintained? I see that the author did not agree with pr

**Comment by alechp** [comment]
> Thank you, Is this repositories still maintained? I see that the author did not agree with pr

I don't think so. Someone submitted a PR (https://github.com/aakashns/create-component-lib/pull/8) within a week of me creating this issue. That was over a year ago
